/* stm32f4xx I2C fsm transition */
typedef struct stm32f4xx_i2c_fsm_trans_s
{
	/* State of origin  */
	stm32f4xx_i2c_fsm_state_t           org_st;     
	/* Transition Condition */
	stm32f4xx_i2c_fsm_condition_func_t  condition;  
	/* Destination state */
	stm32f4xx_i2c_fsm_state_t           dst_st;     
	/* Output generated by the transition */
	stm32f4xx_i2c_fsm_output_func_t     output;     
}stm32f4xx_i2c_fsm_trans_t;