int  i2c_bus_busy(I2CBus *bus);
int  i2c_start_transfer(I2CBus *bus, uint8_t address, bool is_recv);
int  i2c_start_recv(I2CBus *bus, uint8_t address);
int  i2c_start_send(I2CBus *bus, uint8_t address);
int  i2c_start_send_async(I2CBus *bus, uint8_t address);
void i2c_schedule_pending_master(I2CBus *bus);
void i2c_end_transfer(I2CBus *bus);
void i2c_nack(I2CBus *bus);
void i2c_ack(I2CBus *bus);
void i2c_bus_master(I2CBus *bus, QEMUBH *bh);
void i2c_bus_release(I2CBus *bus);
int  i2c_send(I2CBus *bus, uint8_t data);
int  i2c_send_async(I2CBus *bus, uint8_t data);
uint8_t i2c_recv(I2CBus *bus);